import { wordPicker } from './wordPicker';
import { d6 } from '../components/Attribute';

export const maleNames = [
  'Karl',
  'Nigel',
  'Ackley',
  'Ackerley',
  'Addison',
  'Aldrich',
  'Roderick',
  'Broderick',
  'Calder',
  'Cynric',
  'Dudley',
  'Eldridge',
  'Desmond',
  'Esmund',
  'Leland',
  'Llewellyn',
  'Adolphus',
  'Albrecht',
  'Edsel',
  'Finbar'
];

export const femaleNames = [
  'Adalia',
  'Adelaide',
  'Agatha',
  'Albertyne',
  'Arabella',
  'Bathilda',
  'Berta',
  'Beth',
  'Brunhilda',
  'Clementine',
  'Edda',
  'Edwina',
  'Gail',
  'Goldie',
  'Good Mother',
  'Granny',
  'Gytha',
  'Harva',
  'Nanny'
]

export const nbNames = [
  'Alex',
  'Kimberly',
  'Leigh',
  'Morven',
  'Ogden'
]

export const lastNames = [
  'Baldwynn',
  'Ballard',
  'Bloodaxe',
  'Bloodhammer',
  'Booth',
  'Brightaxe',
  'Brighthammer',
  'Brook',
  'Caldwell',
  'Chilton',
  'Dalton',
  'Egerton',
  'Fairfax',
  'Fairfield',
  'Lyndon',
  'Makepeace',
  'Marden',
  'Marley',
  'Marwood',
  'Miller',
  'Pelham',
  'Pelton',
  'Penn',
  'Radclyffe',
  'Radford',
  'Ramsey',
  'Silveraxe',
  'Silverhammer',
  'Silvermoon',
  'Tallmoon'
]

export const elfSyllables = [
  'al',
  'am',
  'ar',
  'ast',
  'av',
  'dal',
  'dar',
  'dor',
  'el',
  'em',
  'fal',
  'mar',
  'nur',
  'sil',
  'sur',
  'tal',
  'tan',
  'tel',
  'vell'
]

export const elfEndings = [
  'ir',
  'il',
  'ion',
  'iel'
]

export const desc1 = [
  'gangly',
  'tall',
  'slender',
  'lithe',
  'musclebound',
  'pudgy',
  'scarred',
  'hirsute',
  'twitchy',
  'warty',
  'wrinkled',
  'sunburnt',
  'handsome',
  'unwashed',
  'filthy',
  'blank-faced'
]

export const desc2 = [
  'bald',
  'boil-ridden',
  'chews tobacco',
  'constantly trying to sell the party something.',
  'eats while they talk',
  'grins toothlessly',
  'has a thick moustache',
  'has a wheezing cough',
  'has long, flowing hair',
  'hums',
  'licks their lips',
  'missing a hand',
  'missing a leg',
  'missing an eye',
  'mumbles',
  'reeks of cloying perfume',
  'smokes a foul pipe',
  'speaks out of the corner of their mouth',
  'speaks slowly',
  'speaks with a strange accent',
  'spits on the floor constantly',
  'stares at nothing',
  'stinks of liquor',
  'tends to ramble',
  'wears fine clothing',
  'whistles constantly',
]

export const desc3 = [
  'giggling',
  'morose',
  'nervous',
  'paranoid',
  'drunken',
  'lecherous',
  'solemn',
  'dignified',
  'chivalrous',
  'friendly',
  'warm',
  'neurotic',
  'hospitable',
  'begrudging',
  'bored',
  'sleepy',
  'frantic',
  'abstemious',
  'snooty',
  'miserable',
  'witty',
  'angry',
  'brooding',
  'sinister',
  'scowling',
  'sly',
  'loquacious'
]

export const species = [
  'dark elf',
  'dragonborn',
  'dwarf',
  'dwarf',
  'elf',
  'elf',
  'gnome',
  'half-elf',
  'half-orc',
  'halfling',
  'human',
  'human',
  'human',
  'human',
  'human',
  'human',
  'lizardfolk',
  'tiefling'
]

export const charJob = [
  'baker',
  'blacksmith',
  'brewer',
  'butcher',
  'carpenter',
  'cook',
  'farmer',
  'farmhand',
  'locksmith',
  'merchant',
  'miller',
  'roofer',
  'shoemaker',
  'soldier',
  'stonemason',
  'tailor',
  'tanner',
  'tax collector',
  'town drunk',
  'village idiot',
  'watchman',
  'weaver',
  'wheelwright',
  'winemaker'
]

export const monsters = [
  'a necromancer',
  'bandits',
  'cultists',
  'goblins',
  'kobolds',
  'lizard people',
  'orcs',
  'undead'
];

export const locations = [
  "cave",
  "dungeon",
  "forest",
  "local bigwig's house",
  "old church",
  "ruined castle",
  "ruined temple",
  "sewer",
];

export const secrets = [
  'is an assassin sent after the party',
  'is an assassin targeting an important NPC',
  'belongs to a cult that meets in the ' + wordPicker(locations, 1),
  'hides a fortune in jewels in the ' + wordPicker(locations, 1),
  'will attempt to poison someone',
  'is plotting with ' + wordPicker(monsters, 1),
]

export const rumours = [
  `the local ${wordPicker(charJob, 1)} is an assassin`,
  `the local ${wordPicker(charJob, 1)} is having a secret love affair`,
  `the ${wordPicker(charJob, 1)} is in league with ${wordPicker(monsters, 1)}`,
  `the ${wordPicker(locations, 1)} has a hidden treasure`,
  `the ${wordPicker(locations, 1)} is infested with ${wordPicker(monsters, 1)}`,
  `don't trust the ${wordPicker(charJob, 1)}`,
  `the ${wordPicker(charJob, 1)} seems mean but has a heart of gold`,
  `the ${wordPicker(charJob, 1)}'s child was stolen by ${wordPicker(monsters, 1)}`,
  `the ${wordPicker(charJob, 1)} sneaks off to the ${wordPicker(locations, 1)} at night`,
  `the local farm animals have been acting strangely`,
  `the ${wordPicker(charJob, 1)} is fond of cats`,
  `the local bigwig is in league with ${wordPicker(monsters, 1)}`,
  `the local bigwig is secretly penniless`,
  `strange visitors left town just a few days ago`,
  `there's a hidden door in the ${wordPicker(locations, 1)}`,
  `something strange is going on in the tavern basement`,
  `the blacksmith hates elves`,
  `the ${wordPicker(charJob, 1)} sells magic items looted from the bodies of dead adventurers`,
  `a local shopkeep will buy and sell stolen goods`,
];

export const items = [
  `${4 * d6()} copper pieces`,
  `${2 * d6()} silver pieces`,
  `a rotten sandwich`,
  `a smooth grey stone from the river`,
  `a rusty dagger`,
  `a dried hunk of cheese`,
  `a healing potion`,
  `a dull red gem`,
  `a wooden shield`,
  `a sinister mask`,
  `a key on a silver chain`,
  `a rabbit's foot`,
  `a severed ear`,
  `a lock of hair`,
]